kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      restartPolicy: Always
      containers:
        - resources: {}
          name: jenkins
          env:
            - name: TZ
              value: Asia/Taipei
          ports:
            - name: httpport
              containerPort: 8080
              protocol: TCP
            - name: jnlpport
              containerPort: 50000
              protocol: TCP
          image: 'jenkins/jenkins:lts'
